CREATE TABLE stay (
    id uuid PRIMARY KEY,
    name varchar(255) NOT NULL CHECK (length(trim(name)) > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);

CREATE TABLE room_type (
    id uuid PRIMARY KEY,
    stay_id uuid NOT NULL REFERENCES stay(id),
    name varchar(255) NOT NULL CHECK (length(trim(name)) > 0),
    max_occupancy integer NOT NULL CHECK (max_occupancy > 0),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
);
CREATE INDEX idx_room_type_stay ON room_type(stay_id);

CREATE TABLE supplier_stay_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier varchar(32) NOT NULL,
    external_stay_code varchar(128) NOT NULL CHECK (length(trim(external_stay_code)) > 0),
    stay_id uuid NOT NULL REFERENCES stay(id),
    is_active boolean NOT NULL,
    last_synced_at timestamptz NOT NULL,
    CONSTRAINT uk_supplier_stay UNIQUE (supplier, external_stay_code)
);
CREATE INDEX idx_supplier_stay_active ON supplier_stay_mapping(supplier, is_active);

CREATE TABLE supplier_room_type_mapping (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_stay_mapping_id bigint NOT NULL REFERENCES supplier_stay_mapping(id),
    external_room_type_code varchar(128) NOT NULL CHECK (length(trim(external_room_type_code)) > 0),
    room_type_id uuid NOT NULL REFERENCES room_type(id),
    is_active boolean NOT NULL,
    last_synced_at timestamptz NOT NULL,
    CONSTRAINT uk_supplier_room UNIQUE (supplier_stay_mapping_id, external_room_type_code)
);

CREATE TABLE supplier_catalog_sync_state (
    supplier varchar(32) PRIMARY KEY,
    last_attempted_at timestamptz NOT NULL,
    last_succeeded_at timestamptz,
    last_failure_category varchar(64)
);
